name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

        **Note**: For security vulnerabilities, please see [SECURITY.md](https://github.com/jarkillo/ci-guardian/security/policy) instead.

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: When I try to..., I expect..., but instead...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Install CI Guardian with `pip install ci-guardian`
        2. Run `ci-guardian install` in a git repository
        3. Execute `git commit -m "test"`
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected the hook to install without errors...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, I got an error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      placeholder: |
        ```
        Paste your logs here
        ```
      render: shell

  - type: input
    id: version
    attributes:
      label: CI Guardian Version
      description: What version of CI Guardian are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.12.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (Fedora)
        - Linux (Arch)
        - Linux (Other)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows 11
        - Windows 10
        - WSL2 (Ubuntu)
        - WSL2 (Other)
        - Other
    validations:
      required: true

  - type: dropdown
    id: venv
    attributes:
      label: Virtual Environment
      description: Are you using a virtual environment?
      options:
        - "Yes (venv)"
        - "Yes (virtualenv)"
        - "Yes (conda)"
        - "Yes (poetry)"
        - "No"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, environment variables, configuration files, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am using the latest version of CI Guardian
          required: true
        - label: I have read the documentation
          required: true
